Repository pagopa/pagopa-node-cfg-sync, pull requests merged in 2024-04, with the labels that each got.

#9 [NOD-744] Deploy UAT
  .github/workflows/05h_deploy_with_github_runner.yml
  Dockerfile
  docker/applicationinsights.json
  docker/run.sh
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: patch, size/small

#10 fix PROD heap size, added alert log
  helm/values-prod.yaml
  infra/.terraform.lock.hcl
  src/main/java/it/gov/pagopa/node/cfgsync/service/ApiConfigCacheEhConsumer.java
  src/main/java/it/gov/pagopa/node/cfgsync/service/ApiConfigCacheService.java
  src/main/java/it/gov/pagopa/node/cfgsync/service/StandInManagerEhConsumer.java
  src/main/java/it/gov/pagopa/node/cfgsync/service/StandInManagerService.java
Labels: patch, size/small

#11 Nod 822 viste
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/node/cfgsync/config/ViewNamingStrategy.java
  src/main/java/it/gov/pagopa/node/cfgsync/config/WebMvcConfiguration.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/model/CDIPreferences.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/model/CDIPreferencesView.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/model/ElencoServizi.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/model/ElencoServiziView.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/nexioracle/NexiCdiPreferencesOracleRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/nexioracle/NexiCdiPreferencesViewOracleRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/nexioracle/NexiElencoServiziOracleRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/nexioracle/NexiElencoServiziViewOracleRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/nexipostgres/NexiCdiPreferencesPostgresRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/nexipostgres/NexiCdiPreferencesViewPostgresRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/nexipostgres/NexiElencoServiziPostgresRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/nexipostgres/NexiElencoServiziViewPostgresRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/pagopa/PagoPaCdiPreferencesPostgresRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/pagopa/PagoPaCdiPreferencesViewPostgresRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/pagopa/PagoPaElencoServiziPostgresRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/repository/pagopa/PagoPaElencoServiziViewPostgresRepository.java
  src/main/java/it/gov/pagopa/node/cfgsync/service/ApiConfigCacheService.java
  src/main/java/it/gov/pagopa/node/cfgsync/util/Constants.java
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
  src/test/java/it/gov/pagopa/node/cfgsync/CacheSyncNexiOracleTest.java
  src/test/java/it/gov/pagopa/node/cfgsync/CacheSyncNexiPostgresTest.java
  src/test/java/it/gov/pagopa/node/cfgsync/CacheSyncTest.java
  src/test/resources/application.yaml
  src/test/resources/logback-spring.xml
Labels: patch, size/large

#13 Tuning UAT
  helm/values-uat.yaml
Labels: ignore-for-release, size/small
